package schema

import (
	"time"

	"entgo.io/ent"
	"entgo.io/ent/schema/field"
	"entgo.io/ent/schema/index"
)

// AIUsageDaily stores AI usage aggregated by day, user, model, and skill.
//
// It is generated by scheduled jobs that aggregate data from ai_call_log.
// It is intended for long-term retention: each row is about 100 bytes, about 10 KB per user per year, and still only MB-scale even for thousands of users.
//
// It is used for monthly user billing, cost dashboards, model usage share, and skill popularity analysis.
type AIUsageDaily struct {
	ent.Schema
}

// Fields of the AIUsageDaily.
func (AIUsageDaily) Fields() []ent.Field {
	return []ent.Field{
		field.Int64("id").
			Unique().
			Comment("Snowflake ID"),

		// Aggregation dimensions, with a composite unique key on date + owner_id + model + skill
		field.Time("date").
			SchemaType(map[string]string{
				"postgres": "date",
				"sqlite3":  "date",
				"mysql":    "date",
			}).
			Comment("statistics date (YYYY-MM-DD only, UTC)"),

		field.Int64("owner_id").
			Comment("owner user"),

		field.String("provider").
			MaxLen(32).
			Comment("LLM provider"),

		field.String("model").
			MaxLen(100).
			Comment("model ID"),

		field.String("skill").
			MaxLen(64).
			Comment("skill name"),

		// Aggregated metrics
		field.Int("call_count").
			Default(0).
			Comment("daily invocation count"),

		field.Int("success_count").
			Default(0).
			Comment("success count"),

		field.Int("error_count").
			Default(0).
			Comment("failure count"),

		field.Int64("input_tokens").
			Default(0).
			Comment("cumulative input tokens"),

		field.Int64("output_tokens").
			Default(0).
			Comment("cumulative output tokens"),

		field.Int64("cached_tokens").
			Default(0).
			Comment("cumulative prompt cache hit tokens"),

		field.Float("cost_usd").
			Default(0).
			Comment("estimated daily cost (USD)"),

		field.Time("updated_at").
			Default(time.Now).
			UpdateDefault(time.Now).
			Comment("last update time of the aggregation job"),
	}
}

// Indexes of the AIUsageDaily.
func (AIUsageDaily) Indexes() []ent.Index {
	return []ent.Index{
		// Unique constraint for the aggregation dimensions, used as the basis for UPSERT
		index.Fields("date", "owner_id", "provider", "model", "skill").Unique(),
		// User billing: query by user and time range
		index.Fields("owner_id", "date"),
	}
}
