package schema

import (
	"time"

	"entgo.io/ent"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
	"entgo.io/ent/schema/index"
)

// Group is the grouping entity used to organize and categorize snippets.
// It supports nested directory structures through a self-referencing parent_id.
type Group struct {
	ent.Schema
}

// Fields of the Group.
func (Group) Fields() []ent.Field {
	return []ent.Field{
		// Primary key generated by the id-generator Snowflake service
		field.Int64("id").
			Comment("globally unique ID generated by Snowflake"),

		field.Int64("owner_id").
			Positive().
			Comment("user ID of the group owner"),

		field.Int64("parent_id").
			Optional().
			Nillable().
			Comment("parent group ID; nil means a top-level group"),

		field.String("name").
			NotEmpty().
			MaxLen(60).
			Comment("group name"),

		field.String("description").
			Optional().
			MaxLen(200).
			Default("").
			Comment("group description"),

		field.Int("sort_order").
			Default(0).
			Comment("sort weight; smaller values appear first"),

		field.Time("created_at").
			Default(time.Now).
			Immutable().
			Comment("creation time"),

		field.Time("updated_at").
			Default(time.Now).
			UpdateDefault(time.Now).
			Comment("last update time"),
	}
}

// Edges of the Group.
func (Group) Edges() []ent.Edge {
	return []ent.Edge{
		// Group -> Snippet, one-to-many
		edge.To("snippets", Snippet.Type),

		// Self-reference: parent -> children
		edge.To("children", Group.Type).
			From("parent").
			Field("parent_id").
			Unique(),
	}
}

// Indexes of the Group.
func (Group) Indexes() []ent.Index {
	return []ent.Index{
		index.Fields("owner_id"),
		index.Fields("owner_id", "name").Unique(),
		index.Fields("owner_id", "parent_id"),
	}
}
