package schema

import (
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
	"entgo.io/ent/schema/index"
)

// Share is the document sharing entity.
type Share struct {
	ent.Schema
}

// Fields of the Share.
func (Share) Fields() []ent.Field {
	return []ent.Field{
		field.Int64("id").
			Comment("globally unique ID generated by Snowflake"),
		field.String("token").
			Unique().
			NotEmpty().
			MaxLen(64).
			Comment("public share token"),
		field.Enum("kind").
			Values("article", "template").
			Default("article").
			Comment("share type: article=document template=template"),
		field.Int64("snippet_id").
			Positive().
			Comment("associated document ID"),
		field.Int64("owner_id").
			Positive().
			Comment("share creator ID"),
		field.String("password_hash").
			Optional().
			MaxLen(255).
			Comment("optional password hash"),
		field.Time("expires_at").
			Optional().
			Nillable().
			Comment("optional expiration time"),
		field.Int("view_count").
			Default(0).
			Comment("view count"),
		field.Int("fork_count").
			Default(0).
			Comment("template fork count"),
		field.Time("created_at").
			Default(time.Now).
			Immutable().
			Comment("creation time"),
	}
}

// Edges of the Share.
func (Share) Edges() []ent.Edge {
	return []ent.Edge{
		edge.From("snippet", Snippet.Type).
			Ref("shares").
			Field("snippet_id").
			Unique().
			Required().
			Annotations(entsql.Annotation{
				OnDelete: entsql.Cascade,
			}),
	}
}

// Indexes of the Share.
func (Share) Indexes() []ent.Index {
	return []ent.Index{
		index.Fields("owner_id"),
		index.Fields("snippet_id"),
		index.Fields("kind"),
	}
}
