package schema

import (
	"time"

	"entgo.io/ent"
	"entgo.io/ent/schema/field"
	"entgo.io/ent/schema/index"
)

// SnippetAIMetadata stores AI enrichment results for documents.
//
// It has a 1:1 relationship with Snippet, with snippet_id as the primary key.
// It is independent of the Snippet table, so AI data can be cleared, recomputed, or migrated without affecting core business data.
type SnippetAIMetadata struct {
	ent.Schema
}

// Fields of the SnippetAIMetadata.
func (SnippetAIMetadata) Fields() []ent.Field {
	return []ent.Field{
		field.Int64("id").
			Unique().
			Comment("snippet_id, one-to-one with the snippet table"),

		field.Int64("owner_id").
			Comment("document owner ID (stored redundantly for easier queries)"),

		field.Text("summary").
			Optional().
			Comment("one-sentence summary generated by AI"),

		field.JSON("suggested_tags", []string{}).
			Optional().
			Comment("AI-suggested tag candidates (only enter the formal tag system after user confirmation)"),

		field.JSON("extracted_todos", []map[string]any{}).
			Optional().
			Comment("AI-extracted structured todos [{text, priority, done}]"),

		// Idempotency and version tracking
		field.Uint32("content_hash").
			Default(0).
			Comment("FNV-1a hash of the content; skip recomputation when unchanged (formerly ai_version)"),

		field.String("prompt_version").
			Default("v1").
			MaxLen(32).
			Comment("prompt version used to generate this result; allows gradual recomputation after prompt changes"),

		field.String("model").
			Optional().
			MaxLen(100).
			Comment("LLM model name used to generate this result"),

		field.Time("created_at").
			Default(time.Now).
			Immutable().
			Comment("first generated time"),

		field.Time("updated_at").
			Default(time.Now).
			UpdateDefault(time.Now).
			Comment("last update time"),
	}
}

// Indexes of the SnippetAIMetadata.
func (SnippetAIMetadata) Indexes() []ent.Index {
	return []ent.Index{
		index.Fields("owner_id"),
	}
}
