package schema

import (
	"time"

	"entgo.io/ent"
	"entgo.io/ent/schema/field"
	"entgo.io/ent/schema/index"
)

// SnippetLineage records document lineage relationships.
type SnippetLineage struct {
	ent.Schema
}

func (SnippetLineage) Fields() []ent.Field {
	return []ent.Field{
		field.Int64("id").
			Comment("globally unique ID generated by Snowflake"),
		field.Int64("snippet_id").
			Positive().
			Unique().
			Comment("current document ID"),
		field.Int64("source_snippet_id").
			Optional().
			Nillable().
			Comment("source document ID"),
		field.Int64("source_share_id").
			Optional().
			Nillable().
			Comment("source share ID"),
		field.Int64("source_user_id").
			Optional().
			Nillable().
			Comment("source author ID"),
		field.Enum("relation_type").
			Values("fork", "import", "duplicate", "template").
			Default("import").
			Comment("source relation type"),
		field.Time("created_at").
			Default(time.Now).
			Immutable().
			Comment("creation time"),
	}
}

func (SnippetLineage) Indexes() []ent.Index {
	return []ent.Index{
		index.Fields("source_snippet_id"),
		index.Fields("source_share_id"),
		index.Fields("relation_type"),
	}
}
