package schema

import (
	"time"

	"entgo.io/ent"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
	"entgo.io/ent/schema/index"
)

// Snippet is the unified entity for code snippets, notes, and files, replacing the previous content model.
// The type field distinguishes content kinds: code for snippets, note for notes, and file for uploads.
type Snippet struct {
	ent.Schema
}

// Fields of the Snippet.
func (Snippet) Fields() []ent.Field {
	return []ent.Field{
		// Primary key generated by the id-generator Snowflake service
		field.Int64("id").
			Comment("globally unique ID generated by Snowflake"),

		field.Int64("owner_id").
			Positive().
			Comment("associated user ID"),

		// Content type separation
		field.Enum("type").
			Values("code", "note", "file").
			Default("code").
			Comment("content type: code=snippet note=note file=uploaded file"),

		field.String("title").
			NotEmpty().
			MaxLen(200).
			Comment("title"),

		// Text content, used for code and note types
		field.Text("content").
			Optional().
			Comment("text content of the code snippet or note"),

		// File metadata, used for file type
		field.String("file_url").
			Optional().
			MaxLen(512).
			Comment("object storage path of the file"),

		field.Int64("file_size").
			Optional().
			Default(0).
			Comment("file size in bytes"),

		field.String("mime_type").
			Optional().
			MaxLen(100).
			Comment("file MIME type"),

		// Programming language
		field.String("language").
			Default("text").
			MaxLen(30).
			Comment("programming language or file type identifier"),

		// Group association
		field.Int64("group_id").
			Optional().
			Nillable().
			Comment("owning group ID"),

		// Sorting
		field.Int("sort_order").
			Default(0).
			Comment("sort weight within the group; smaller values appear first and support drag-and-drop ordering"),

		// Additional metadata
		field.Bool("is_favorite").
			Default(false).
			Comment("whether the item is starred"),

		field.Time("deleted_at").
			Optional().
			Nillable().
			Comment("deletion time; a non-nil value means the item is in the recycle bin (soft deleted)"),

		// Timestamps
		field.Time("created_at").
			Default(time.Now).
			Immutable().
			Comment("creation time"),

		field.Time("updated_at").
			Default(time.Now).
			UpdateDefault(time.Now).
			Comment("last update time"),
	}
}

// Edges of the Snippet.
func (Snippet) Edges() []ent.Edge {
	return []ent.Edge{
		// Snippet -> Group, many-to-one
		edge.From("group", Group.Type).
			Ref("snippets").
			Field("group_id").
			Unique(),

		// Snippet <-> Tag, many-to-many
		edge.To("tags", Tag.Type),

		// Snippet <- Share, one-to-many
		edge.To("shares", Share.Type),
	}
}

// Indexes of the Snippet.
func (Snippet) Indexes() []ent.Index {
	return []ent.Index{
		index.Fields("owner_id"),
		index.Fields("owner_id", "deleted_at"),
		index.Fields("owner_id", "is_favorite"),
		index.Fields("owner_id", "type"),
		index.Fields("owner_id", "group_id"),
		index.Fields("owner_id", "group_id", "sort_order"),
	}
}
