package schema

import (
	"time"

	"entgo.io/ent"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
	"entgo.io/ent/schema/index"
)

// Tag is the tag entity used to label snippets through a many-to-many relationship.
type Tag struct {
	ent.Schema
}

// Fields of the Tag.
func (Tag) Fields() []ent.Field {
	return []ent.Field{
		// Primary key generated by the id-generator Snowflake service
		field.Int64("id").
			Comment("globally unique ID generated by Snowflake"),

		field.Int64("owner_id").
			Positive().
			Comment("user ID of the tag owner"),

		field.String("name").
			NotEmpty().
			MaxLen(30).
			Comment("tag name"),

		field.String("color").
			Optional().
			MaxLen(7).
			Default("#6366f1").
			Comment("tag color HEX value"),

		field.Time("created_at").
			Default(time.Now).
			Immutable().
			Comment("creation time"),
	}
}

// Edges of the Tag.
func (Tag) Edges() []ent.Edge {
	return []ent.Edge{
		// Tag <-> Snippet, many-to-many and reverse-linked
		edge.From("snippets", Snippet.Type).
			Ref("tags"),
	}
}

// Indexes of the Tag.
func (Tag) Indexes() []ent.Index {
	return []ent.Index{
		index.Fields("owner_id"),
		index.Fields("owner_id", "name").Unique(),
	}
}
