package schema

import (
	"time"

	"entgo.io/ent"
	"entgo.io/ent/schema/field"
	"entgo.io/ent/schema/index"
)

// Template is the document template entity.
// It supports both built-in system templates (is_system=true, owner_id=0) and user-owned personal templates.
type Template struct {
	ent.Schema
}

// Fields of the Template.
func (Template) Fields() []ent.Field {
	return []ent.Field{
		// Primary key generated by the id-generator Snowflake service
		field.Int64("id").
			Comment("globally unique ID generated by Snowflake"),

		field.Int64("owner_id").
			Default(0).
			Comment("creator user ID, 0 = built-in system template"),

		field.String("name").
			NotEmpty().
			MaxLen(100).
			Comment("template name"),

		field.String("description").
			Optional().
			Default("").
			MaxLen(500).
			Comment("template description"),

		field.Text("content").
			Comment("template content (Markdown)"),

		field.String("language").
			Default("markdown").
			MaxLen(30).
			Comment("language identifier"),

		field.String("category").
			Default("general").
			MaxLen(30).
			Comment("category: general / meeting / tech_design / weekly_report"),

		field.Bool("is_system").
			Default(false).
			Comment("whether this is a system preset template"),

		field.Time("created_at").
			Default(time.Now).
			Immutable().
			Comment("creation time"),

		field.Time("updated_at").
			Default(time.Now).
			UpdateDefault(time.Now).
			Comment("last update time"),
	}
}

// Indexes of the Template.
func (Template) Indexes() []ent.Index {
	return []ent.Index{
		index.Fields("owner_id"),
		index.Fields("category"),
		index.Fields("is_system"),
	}
}
