// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/ownforge/ownforge/services/notes/internal/ent/aicalllog"
)

// AICallLog is the model entity for the AICallLog schema.
type AICallLog struct {
	config `json:"-"`
	// ID of the ent.
	// Snowflake ID
	ID int64 `json:"id,omitempty"`
	// Owning user, used for quotas, billing, and data isolation
	OwnerID int64 `json:"owner_id,omitempty"`
	// Skill name, such as enrich, weekly_report, or smart_search
	Skill string `json:"skill,omitempty"`
	// Related snippet, when present, for document-level tracing
	SnippetID *int64 `json:"snippet_id,omitempty"`
	// openai / anthropic / ollama / ...
	Provider string `json:"provider,omitempty"`
	// Concrete model ID, such as gpt-4o-mini or claude-3-5-sonnet
	Model string `json:"model,omitempty"`
	// Prompt version used for regression comparison
	PromptVersion string `json:"prompt_version,omitempty"`
	// Hash of the input messages, using the first 16 bytes of sha256 in hex
	InputHash string `json:"input_hash,omitempty"`
	// Input token count
	InputTokens int `json:"input_tokens,omitempty"`
	// Output token count
	OutputTokens int `json:"output_tokens,omitempty"`
	// Number of tokens served from the prompt cache
	CachedTokens int `json:"cached_tokens,omitempty"`
	// Estimated cost of this call in USD
	CostUsd float64 `json:"cost_usd,omitempty"`
	// Call latency in milliseconds
	LatencyMs int `json:"latency_ms,omitempty"`
	// Call result status
	Status aicalllog.Status `json:"status,omitempty"`
	// Truncated error message, filled when status != success
	Error string `json:"error,omitempty"`
	// Call time
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AICallLog) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case aicalllog.FieldCostUsd:
			values[i] = new(sql.NullFloat64)
		case aicalllog.FieldID, aicalllog.FieldOwnerID, aicalllog.FieldSnippetID, aicalllog.FieldInputTokens, aicalllog.FieldOutputTokens, aicalllog.FieldCachedTokens, aicalllog.FieldLatencyMs:
			values[i] = new(sql.NullInt64)
		case aicalllog.FieldSkill, aicalllog.FieldProvider, aicalllog.FieldModel, aicalllog.FieldPromptVersion, aicalllog.FieldInputHash, aicalllog.FieldStatus, aicalllog.FieldError:
			values[i] = new(sql.NullString)
		case aicalllog.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AICallLog fields.
func (_m *AICallLog) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case aicalllog.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case aicalllog.FieldOwnerID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field owner_id", values[i])
			} else if value.Valid {
				_m.OwnerID = value.Int64
			}
		case aicalllog.FieldSkill:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field skill", values[i])
			} else if value.Valid {
				_m.Skill = value.String
			}
		case aicalllog.FieldSnippetID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field snippet_id", values[i])
			} else if value.Valid {
				_m.SnippetID = new(int64)
				*_m.SnippetID = value.Int64
			}
		case aicalllog.FieldProvider:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider", values[i])
			} else if value.Valid {
				_m.Provider = value.String
			}
		case aicalllog.FieldModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model", values[i])
			} else if value.Valid {
				_m.Model = value.String
			}
		case aicalllog.FieldPromptVersion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field prompt_version", values[i])
			} else if value.Valid {
				_m.PromptVersion = value.String
			}
		case aicalllog.FieldInputHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field input_hash", values[i])
			} else if value.Valid {
				_m.InputHash = value.String
			}
		case aicalllog.FieldInputTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field input_tokens", values[i])
			} else if value.Valid {
				_m.InputTokens = int(value.Int64)
			}
		case aicalllog.FieldOutputTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field output_tokens", values[i])
			} else if value.Valid {
				_m.OutputTokens = int(value.Int64)
			}
		case aicalllog.FieldCachedTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field cached_tokens", values[i])
			} else if value.Valid {
				_m.CachedTokens = int(value.Int64)
			}
		case aicalllog.FieldCostUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field cost_usd", values[i])
			} else if value.Valid {
				_m.CostUsd = value.Float64
			}
		case aicalllog.FieldLatencyMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field latency_ms", values[i])
			} else if value.Valid {
				_m.LatencyMs = int(value.Int64)
			}
		case aicalllog.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = aicalllog.Status(value.String)
			}
		case aicalllog.FieldError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error", values[i])
			} else if value.Valid {
				_m.Error = value.String
			}
		case aicalllog.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AICallLog.
// This includes values selected through modifiers, order, etc.
func (_m *AICallLog) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this AICallLog.
// Note that you need to call AICallLog.Unwrap() before calling this method if this AICallLog
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AICallLog) Update() *AICallLogUpdateOne {
	return NewAICallLogClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AICallLog entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AICallLog) Unwrap() *AICallLog {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AICallLog is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AICallLog) String() string {
	var builder strings.Builder
	builder.WriteString("AICallLog(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("owner_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.OwnerID))
	builder.WriteString(", ")
	builder.WriteString("skill=")
	builder.WriteString(_m.Skill)
	builder.WriteString(", ")
	if v := _m.SnippetID; v != nil {
		builder.WriteString("snippet_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("provider=")
	builder.WriteString(_m.Provider)
	builder.WriteString(", ")
	builder.WriteString("model=")
	builder.WriteString(_m.Model)
	builder.WriteString(", ")
	builder.WriteString("prompt_version=")
	builder.WriteString(_m.PromptVersion)
	builder.WriteString(", ")
	builder.WriteString("input_hash=")
	builder.WriteString(_m.InputHash)
	builder.WriteString(", ")
	builder.WriteString("input_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.InputTokens))
	builder.WriteString(", ")
	builder.WriteString("output_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.OutputTokens))
	builder.WriteString(", ")
	builder.WriteString("cached_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.CachedTokens))
	builder.WriteString(", ")
	builder.WriteString("cost_usd=")
	builder.WriteString(fmt.Sprintf("%v", _m.CostUsd))
	builder.WriteString(", ")
	builder.WriteString("latency_ms=")
	builder.WriteString(fmt.Sprintf("%v", _m.LatencyMs))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("error=")
	builder.WriteString(_m.Error)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// AICallLogs is a parsable slice of AICallLog.
type AICallLogs []*AICallLog
