// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/ownforge/ownforge/services/notes/internal/ent/aiusagedaily"
)

// AIUsageDaily is the model entity for the AIUsageDaily schema.
type AIUsageDaily struct {
	config `json:"-"`
	// ID of the ent.
	// Snowflake ID
	ID int64 `json:"id,omitempty"`
	// Aggregation date in YYYY-MM-DD format, UTC only
	Date time.Time `json:"date,omitempty"`
	// Owning user
	OwnerID int64 `json:"owner_id,omitempty"`
	// LLM provider
	Provider string `json:"provider,omitempty"`
	// Model ID
	Model string `json:"model,omitempty"`
	// Skill name
	Skill string `json:"skill,omitempty"`
	// Number of calls for the day
	CallCount int `json:"call_count,omitempty"`
	// Number of successful calls
	SuccessCount int `json:"success_count,omitempty"`
	// Number of failed calls
	ErrorCount int `json:"error_count,omitempty"`
	// Total input tokens
	InputTokens int64 `json:"input_tokens,omitempty"`
	// Total output tokens
	OutputTokens int64 `json:"output_tokens,omitempty"`
	// Total prompt-cache-hit tokens
	CachedTokens int64 `json:"cached_tokens,omitempty"`
	// Estimated daily cost in USD
	CostUsd float64 `json:"cost_usd,omitempty"`
	// Last update time of the aggregation job
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AIUsageDaily) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case aiusagedaily.FieldCostUsd:
			values[i] = new(sql.NullFloat64)
		case aiusagedaily.FieldID, aiusagedaily.FieldOwnerID, aiusagedaily.FieldCallCount, aiusagedaily.FieldSuccessCount, aiusagedaily.FieldErrorCount, aiusagedaily.FieldInputTokens, aiusagedaily.FieldOutputTokens, aiusagedaily.FieldCachedTokens:
			values[i] = new(sql.NullInt64)
		case aiusagedaily.FieldProvider, aiusagedaily.FieldModel, aiusagedaily.FieldSkill:
			values[i] = new(sql.NullString)
		case aiusagedaily.FieldDate, aiusagedaily.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AIUsageDaily fields.
func (_m *AIUsageDaily) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case aiusagedaily.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case aiusagedaily.FieldDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field date", values[i])
			} else if value.Valid {
				_m.Date = value.Time
			}
		case aiusagedaily.FieldOwnerID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field owner_id", values[i])
			} else if value.Valid {
				_m.OwnerID = value.Int64
			}
		case aiusagedaily.FieldProvider:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider", values[i])
			} else if value.Valid {
				_m.Provider = value.String
			}
		case aiusagedaily.FieldModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model", values[i])
			} else if value.Valid {
				_m.Model = value.String
			}
		case aiusagedaily.FieldSkill:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field skill", values[i])
			} else if value.Valid {
				_m.Skill = value.String
			}
		case aiusagedaily.FieldCallCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field call_count", values[i])
			} else if value.Valid {
				_m.CallCount = int(value.Int64)
			}
		case aiusagedaily.FieldSuccessCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field success_count", values[i])
			} else if value.Valid {
				_m.SuccessCount = int(value.Int64)
			}
		case aiusagedaily.FieldErrorCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field error_count", values[i])
			} else if value.Valid {
				_m.ErrorCount = int(value.Int64)
			}
		case aiusagedaily.FieldInputTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field input_tokens", values[i])
			} else if value.Valid {
				_m.InputTokens = value.Int64
			}
		case aiusagedaily.FieldOutputTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field output_tokens", values[i])
			} else if value.Valid {
				_m.OutputTokens = value.Int64
			}
		case aiusagedaily.FieldCachedTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field cached_tokens", values[i])
			} else if value.Valid {
				_m.CachedTokens = value.Int64
			}
		case aiusagedaily.FieldCostUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field cost_usd", values[i])
			} else if value.Valid {
				_m.CostUsd = value.Float64
			}
		case aiusagedaily.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AIUsageDaily.
// This includes values selected through modifiers, order, etc.
func (_m *AIUsageDaily) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this AIUsageDaily.
// Note that you need to call AIUsageDaily.Unwrap() before calling this method if this AIUsageDaily
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AIUsageDaily) Update() *AIUsageDailyUpdateOne {
	return NewAIUsageDailyClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AIUsageDaily entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AIUsageDaily) Unwrap() *AIUsageDaily {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AIUsageDaily is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AIUsageDaily) String() string {
	var builder strings.Builder
	builder.WriteString("AIUsageDaily(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("date=")
	builder.WriteString(_m.Date.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("owner_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.OwnerID))
	builder.WriteString(", ")
	builder.WriteString("provider=")
	builder.WriteString(_m.Provider)
	builder.WriteString(", ")
	builder.WriteString("model=")
	builder.WriteString(_m.Model)
	builder.WriteString(", ")
	builder.WriteString("skill=")
	builder.WriteString(_m.Skill)
	builder.WriteString(", ")
	builder.WriteString("call_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.CallCount))
	builder.WriteString(", ")
	builder.WriteString("success_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.SuccessCount))
	builder.WriteString(", ")
	builder.WriteString("error_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.ErrorCount))
	builder.WriteString(", ")
	builder.WriteString("input_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.InputTokens))
	builder.WriteString(", ")
	builder.WriteString("output_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.OutputTokens))
	builder.WriteString(", ")
	builder.WriteString("cached_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.CachedTokens))
	builder.WriteString(", ")
	builder.WriteString("cost_usd=")
	builder.WriteString(fmt.Sprintf("%v", _m.CostUsd))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// AIUsageDailies is a parsable slice of AIUsageDaily.
type AIUsageDailies []*AIUsageDaily
