package schema

import (
	"time"

	"entgo.io/ent"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
)

// User holds the schema definition for the User entity.
type User struct {
	ent.Schema
}

// Fields of the User.
func (User) Fields() []ent.Field {
	return []ent.Field{
		// 1. Primary key: generated by Snowflake
		field.Int64("id").
			Positive(),

		// 1.1 User global version: used for global invalidation control
		field.Int64("user_version").
			Default(1).
			Comment("user global version"),

		// 2. Status: the aggregate only stores account lifecycle state
		field.Enum("status").
			Values("active", "banned", "deleted").
			Default("active").
			Comment("user account status"),

		// 3. Creation time: generated automatically on insert and immutable afterward
		field.Time("created_at").
			Default(time.Now).
			Immutable().
			Comment("creation time"),

		// 4. Update time: Ent automatically refreshes this field on every update
		field.Time("updated_at").
			Default(time.Now).
			UpdateDefault(time.Now). // No need to update timestamps manually in business code.
			Comment("last update time"),
	}
}

func (User) Edges() []ent.Edge {
	return []ent.Edge{
		// One-to-one: one User owns one Profile
		edge.To("profile", Profile.Type).Unique(),
		// One-to-many: one User can bind multiple login identities
		edge.To("identities", UserIdentity.Type),
		// One-to-many: one User can have multiple app authorizations
		edge.To("authorizations", UserAppAuthorization.Type),
		// One-to-many: one User can have multiple global SSO sessions
		edge.To("sso_sessions", SsoSession.Type),
		// One-to-many: one User can have multiple sessions
		edge.To("sessions", Session.Type),
	}
}
